# Generated by Django 6.0.2 on 2026-02-04 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Nivel de Grado',
                'verbose_name_plural': 'Niveles de Grado',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Área/Materia',
                'verbose_name_plural': 'Áreas/Materias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Examen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.gradelevel', verbose_name='Nivel de Grado')),
                ('subject_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.subjectarea', verbose_name='Área/Materia')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: EA01, EA02', max_length=20, verbose_name='Código')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('instruction', models.TextField(help_text='Ej: ¿Qué se ve en el dibujo? Marca la palabra correcta.', verbose_name='Instrucción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/items/', verbose_name='Imagen')),
                ('scoring_type', models.CharField(choices=[('D', 'Dicotómico (0=incorrecto, 1=correcto)'), ('P', 'Politómico (0=incorrecto, 1=parcial, 2=correcto)')], default='D', max_length=1, verbose_name='Tipo de Calificación')),
                ('correct_criteria', models.TextField(blank=True, help_text='Descripción de cuándo la respuesta es correcta', verbose_name='Criterio Correcta')),
                ('partial_criteria', models.TextField(blank=True, help_text='Descripción de cuándo la respuesta es parcialmente correcta', verbose_name='Criterio Parcialmente Correcta')),
                ('incorrect_criteria', models.TextField(blank=True, help_text='Descripción de cuándo la respuesta es incorrecta', verbose_name='Criterio Incorrecta')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['order'],
                'unique_together': {('exam', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/subquestions/', verbose_name='Imagen')),
                ('context_text', models.CharField(blank=True, help_text='Texto adicional si aplica (ej: descripción de imagen)', max_length=500, verbose_name='Texto de contexto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='exams.item', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Subpregunta',
                'verbose_name_plural': 'Subpreguntas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ej: a, b, c, d', max_length=5, verbose_name='Etiqueta')),
                ('text', models.CharField(help_text='Texto de la opción', max_length=500, verbose_name='Texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.subquestion', verbose_name='Subpregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['order'],
            },
        ),
    ]
