# Generated by Django 6.0.2 on 2026-02-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='context_text',
            field=models.TextField(blank=True, help_text='Contenido de la subpregunta (puede incluir texto, tablas, imágenes)', verbose_name='Contenido'),
        ),
    ]
