# Generated by Django 6.0.2 on 2026-02-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_subquestion_context_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject_area',
        ),
    ]
