# Generated by Django 6.0.2 on 2026-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_description_remove_exam_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='question_type',
            field=models.CharField(choices=[('C', 'Cerrada (opciones)'), ('O', 'Abierta (texto libre)')], default='C', max_length=1, verbose_name='Tipo de pregunta'),
        ),
    ]
