# Generated by Django 6.0.2 on 2026-02-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_remove_exam_description_remove_exam_grade_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Aplicación Marzo 2026', max_length=255, verbose_name='Nombre de la aplicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Aplicación de Examen',
                'verbose_name_plural': 'Aplicaciones de Examen',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResponseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Número de fila')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='responses.examapplication', verbose_name='Aplicación')),
            ],
            options={
                'verbose_name': 'Fila de Respuesta',
                'verbose_name_plural': 'Filas de Respuesta',
                'ordering': ['row_number'],
                'unique_together': {('application', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='exams.option', verbose_name='Opción seleccionada')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.subquestion', verbose_name='Subpregunta')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='responses.responserow', verbose_name='Fila')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('row', 'subquestion')},
            },
        ),
    ]
