# Generated by Django 6.0.2 on 2026-02-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_description_remove_exam_grade_level_and_more'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='0=Incorrecta, 1=Parcialmente correcta, 2=Correcta', verbose_name='Puntuación')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.item', verbose_name='Ítem')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_scores', to='responses.responserow', verbose_name='Fila')),
            ],
            options={
                'verbose_name': 'Puntuación de Ítem',
                'verbose_name_plural': 'Puntuaciones de Ítems',
                'unique_together': {('row', 'item')},
            },
        ),
    ]
