# Generated by Django 6.0.2 on 2026-02-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_itemscore'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examapplication',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='students.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='students.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='response',
            name='text_response',
            field=models.TextField(blank=True, help_text='Para preguntas abiertas o sub-preguntas que requieren texto', null=True, verbose_name='Respuesta de texto'),
        ),
        migrations.AddField(
            model_name='responserow',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_rows', to='students.student', verbose_name='Estudiante'),
        ),
    ]
